##### 이번 주는 진도를 나가지 않고, 지금까지 진행한 이론 부분들을 복습하는 겸, 코드 리뷰를 하는 시간을 가졌습니다! 그 중, 기존에 잘 모르고 썼던 sklearn의 lasso를 중점적으로 연습해보았습니다.

Parameter 분석은 https://jungsooyun.github.io/isl%20study/2018/02/07/Ch_6_Lasso_with_python.html
에 업로드 되어있습니다!! 실습 코드에 대한 상세한 설명은 토요일 발제때 하도록 하겠습니다!

In [51]:
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV

In [52]:
data = pd.read_csv('German_Credit.csv', index_col='ID')

In [3]:
data.head()

Checking_account  Duration_in_month  Credit_history  Purpose  \
ID                                                                 
1                  1                  6               4        3   
2                  4                 12               4        6   
3                  1                 42               2        2   
4                  4                 36               2        6   
5                  4                 24               2        2   

    Credit_amount  Saving_accout  Present_employment  Installment_rate  \
ID                                                                       
1            1169              5                   5                 4   
2            2096              1                   4                 2   
3            7882              1                   4                 2   
4            9055              5                   3                 2   
5            2835              3                   5                 3   

    Personal_status___sex  Other_debtors_guarantors      ...        Property  \
ID                                                       ...                   
1                       3                         1      ...               1   
2                       3                         1      ...               1   
3                       3                         3      ...               2   
4                       3                         1      ...               4   
5                       3                         1      ...               2   

    Age  Other_installment_plan  Housing  Num_of_existing_credits  Job  \
ID                                                                       
1    67                       3        2                        2    3   
2    49                       3        2                        1    2   
3    45                       3        3                        1    3   
4    35                       3        3                        1    2   
5    53                       3        2                        1    3   

    Num_of_people_liable  Telephone  Foreign_worker  Credit_status  
ID                                                                  
1                      1          2               1              N  
2                      2          1               1              N  
3                      2          1               1              N  
4                      2          2               1              N  
5                      1          1               1              N  

[5 rows x 21 columns]

In [4]:
data.isnull().any()

Checking_account            False
Duration_in_month           False
Credit_history              False
Purpose                     False
Credit_amount               False
Saving_accout               False
Present_employment          False
Installment_rate            False
Personal_status___sex       False
Other_debtors_guarantors    False
Present_residence           False
Property                    False
Age                         False
Other_installment_plan      False
Housing                     False
Num_of_existing_credits     False
Job                         False
Num_of_people_liable        False
Telephone                   False
Foreign_worker              False
Credit_status               False
dtype: bool

In [5]:
!pip install pandas-profiling

In [6]:
import pandas_profiling

In [7]:
pandas_profiling.ProfileReport(data)


In [8]:
X = data
Y = data['Credit_amount']

In [9]:
dummied_col = pd.get_dummies(X['Credit_status'],prefix='Credit_status')

In [10]:
X = X.join(dummied_col)

In [11]:
X.head()

Checking_account  Duration_in_month  Credit_history  Purpose  \
ID                                                                 
1                  1                  6               4        3   
2                  4                 12               4        6   
3                  1                 42               2        2   
4                  4                 36               2        6   
5                  4                 24               2        2   

    Credit_amount  Saving_accout  Present_employment  Installment_rate  \
ID                                                                       
1            1169              5                   5                 4   
2            2096              1                   4                 2   
3            7882              1                   4                 2   
4            9055              5                   3                 2   
5            2835              3                   5                 3   

    Personal_status___sex  Other_debtors_guarantors       ...         \
ID                                                        ...          
1                       3                         1       ...          
2                       3                         1       ...          
3                       3                         3       ...          
4                       3                         1       ...          
5                       3                         1       ...          

    Other_installment_plan  Housing  Num_of_existing_credits  Job  \
ID                                                                  
1                        3        2                        2    3   
2                        3        2                        1    2   
3                        3        3                        1    3   
4                        3        3                        1    2   
5                        3        2                        1    3   

    Num_of_people_liable  Telephone  Foreign_worker  Credit_status  \
ID                                                                   
1                      1          2               1              N   
2                      2          1               1              N   
3                      2          1               1              N   
4                      2          2               1              N   
5                      1          1               1              N   

    Credit_status_N  Credit_status_Y  
ID                                    
1                 1                0  
2                 1                0  
3                 1                0  
4                 1                0  
5                 1                0  

[5 rows x 23 columns]

In [12]:
import numpy as np

In [13]:
y = np.array(Y)

In [14]:
del(X['Credit_amount'])

In [15]:
del(X['Credit_status'])

In [54]:
lasso = Lasso(alpha=2)

In [56]:
lasso.fit(X,Y)

Lasso(alpha=2, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [18]:
lasso.alpha

1.0

In [42]:
lasso.coef_

array([ -3.34145142e+01,   1.36480273e+02,  -4.36541506e+01,
        -3.83705259e+00,   5.10758915e+01,  -1.59918659e+01,
        -8.11375589e+02,   1.05492396e+02,  -0.00000000e+00,
        -6.05017418e+00,   2.51446849e+02,   1.34398819e+01,
         2.69311932e+01,   1.03380909e+02,   2.41521267e+02,
         5.66802788e+02,  -6.63992233e+01,   6.49930996e+02,
         8.09423953e+02,  -3.15494850e+02,   1.58180852e-13])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25)

In [22]:
lasso.fit(X_train,Y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [23]:
lasso.predict(X_test)

array([  1.60363836e+03,   4.30701415e+03,   2.31765597e+03,
         5.86390320e+03,   1.37333234e+03,   4.34458475e+03,
         5.36038344e+03,   4.53434128e+03,   2.99710586e+03,
         8.77764327e+02,   2.61610706e+03,   2.81356892e+03,
         1.97041930e+03,   5.88730013e+03,   1.04571614e+03,
         8.78258341e+02,   3.61537650e+03,   3.12372303e+03,
        -8.69436290e+00,   5.45027794e+03,   1.11821458e+03,
        -1.10708025e+02,   4.36539809e+03,   7.81542167e+02,
         2.21046059e+03,   2.30941700e+03,   1.64506888e+03,
         2.88772910e+03,   2.66942794e+03,   2.70863937e+02,
         2.61787552e+03,   4.05417480e+03,   5.54775162e+03,
         6.35884100e+03,   1.02452558e+03,   1.50124345e+03,
         5.06109991e+03,   2.56809878e+02,   3.95076844e+03,
         4.38340036e+03,   2.74891696e+03,   4.70358553e+03,
         1.23927290e+03,   2.45167086e+03,   2.82275946e+03,
         2.67771123e+02,   3.18681556e+03,   2.85966828e+03,
         2.89162710e+03,

In [53]:
lassocv = LassoCV(eps = 0.0001, n_alphas = 5000,
                  cv = 5, n_jobs= -1, normalize = True,
                  max_iter=1000000, verbose=True)
lassocv.fit(X_train,Y_train)

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

LassoCV(alphas=None, copy_X=True, cv=5, eps=0.0001, fit_intercept=True,
    max_iter=1000000, n_alphas=5000, n_jobs=-1, normalize=True,
    positive=False, precompute='auto', random_state=None,
    selection='cyclic', tol=0.0001, verbose=True)

In [36]:
lassocv.coef_

array([ -0.00000000e+00,   1.34458347e+02,  -0.00000000e+00,
        -0.00000000e+00,   3.69683887e+00,  -0.00000000e+00,
        -7.46413603e+02,   2.12106118e+01,  -0.00000000e+00,
         0.00000000e+00,   2.32923039e+02,   8.57627655e+00,
        -0.00000000e+00,   3.67337673e+01,   1.14940061e+02,
         4.99692212e+02,   0.00000000e+00,   6.19032291e+02,
         4.75716652e+02,  -2.00224573e+02,   1.79200012e-14])

In [37]:
y_pred = lassocv.predict(X_test)

In [50]:
lassocv.alpha_

2.0205182707371838

In [40]:
y_pred

array([  1626.40772427,   4346.61464509,   2396.11644313,   5627.387428  ,
         1335.24646786,   3999.13387498,   5211.89565363,   4534.17481912,
         3088.58540226,   1196.04413686,   2696.09429598,   2669.00977921,
         2194.1627302 ,   5840.0650314 ,   1320.17850789,    972.96553162,
         3657.61416379,   2996.43585558,    316.38562556,   5459.10166232,
         1282.3214536 ,     78.0357209 ,   4335.62583193,    783.17571078,
         2116.10323324,   2369.6387896 ,   1292.30478197,   2903.12064088,
         2786.26575068,    585.28853768,   2574.89644878,   3950.70679361,
         5593.3436397 ,   6242.92849389,   1051.08577013,   1788.61181315,
         5042.19112892,    542.40419673,   3985.96337044,   4053.71652626,
         2969.44730909,   4759.72688811,   1223.49661997,   2519.39882512,
         2904.75884289,    286.12479625,   3208.69466293,   2715.63346611,
         2784.63452501,   3495.94024519,   1076.34165121,   3885.66205044,
         6545.97593754,  

In [45]:
import math
ans = np.array(y_pred - Y_test)

In [49]:
lassocv.score(X_train, Y_train)

0.55412614473358601

In [48]:
math.sqrt(sum(ans**2))

29481.205920458975